package io.zoemeow.dutapp.model

import com.google.gson.annotations.SerializedName

data class AccountInformationItem(
    val name: String? = null,
    val dateOfBirth: String? = null,
    val birthPlace: String? = null,
    val gender: String? = null,
    val ethnicity: String? = null,
    val nationality: String? = null,
    val nationalIdCard: String? = null,
    val nationalIdCardIssueDate: String? = null,
    val nationalIdCardIssuePlace: String? = null,
    val citizenIdCard: String? = null,
    val citizenIdCardIssueDate: String? = null,
    val religion: String? = null,
    val accountBankId: String? = null,
    val accountBankName: String? = null,
    @SerializedName("hiid") val hIId: String? = null,
    @SerializedName("hiexpiredate") val hIExpireDate: String? = null,
    val specialization: String? = null,
    @SerializedName("class") val schoolClass: String? = null,
    @SerializedName("trainingprogramplan") val trainingProgramPlan: String? = null,
    @SerializedName("trainingprogramplan2") val trainingProgramPlan2: String? = null,
    @SerializedName("schoolemail") val schoolEmail: String? = null,
    @SerializedName("personalemail") val personalEmail: String? = null,
    @SerializedName("schoolemailinitpass") val schoolEmailInitPass: String? = null,
    val facebookUrl: String? = null,
    val phoneNumber: String? = null,
    val address: String? = null,
    val addressFrom: String? = null,
    val addressCity: String? = null,
    val addressDistrict: String? = null,
    val addressSubDistrict: String? = null,
    val studentId: String? = null,
)
