package io.zoemeow.dutapp.model

data class AccountInformationItem(
    val name: String? = null,
    val dateOfBirth: String? = null,
    val birthPlace: String? = null,
    val gender: String? = null,
    val ethnicity: String? = null,
    val nationality: String? = null,
    val nationalIdCard: String? = null,
    val nationalIdCardIssueDate: String? = null,
    val nationalIdCardIssuePlace: String? = null,
    val citizenIdCard: String? = null,
    val citizenIdCardIssueDate: String? = null,
    val religion: String? = null,
    val accountBankId: String? = null,
    val accountBankName: String? = null,
    val hIId: String? = null,
    val hIExpireDate: String? = null,
    val specialization: String? = null,
    val schoolClass: String? = null,
    val trainingProgramPlan: String? = null,
    val trainingProgramPlan2: String? = null,
    val schoolEmail: String? = null,
    val personalEmail: String? = null,
    val schoolEmailInitPass: String? = null,
    val facebookUrl: String? = null,
    val phoneNumber: String? = null,
    val address: String? = null,
    val addressFrom: String? = null,
    val addressCity: String? = null,
    val addressDistrict: String? = null,
    val addressSubDistrict: String? = null,
    val studentId: String? = null,
)
